version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-sendgrid
            source /usr/local/share/virtualenvs/tap-sendgrid/bin/activate
            uv pip install .
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-sendgrid/bin/activate
            uv pip install pylint
            pylint tap_sendgrid --disable missing-docstring,logging-format-interpolation,no-member,broad-except,too-many-branches,missing-final-newline,use-implicit-booleaness-not-len,broad-exception-raised,consider-using-f-string,consider-using-set-comprehension,useless-object-inheritance,too-many-instance-attributes,no-else-return,simplifiable-if-statement,line-too-long,too-few-public-methods,unspecified-encoding,logging-not-lazy,too-many-arguments,redefined-builtin,inconsistent-return-statements,too-many-positional-arguments

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
